/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jiazhu_demo_Mp3Encoder */

#ifndef _Included_com_jiazhu_demo_Mp3EncoderTwo
#define _Included_com_jiazhu_demo_Mp3EncoderTwo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jiazhu_demo_Mp3Encoder
 * Method:    init
 * Signature: (IIIII)V
 */
JNIEXPORT jint JNICALL Java_com_jiazhu_demo_encoder_Mp3EncoderTwo_init
  (JNIEnv *, jobject, jstring, jint, jint, jint, jstring);

/*
 * Class:     com_jiazhu_demo_Mp3Encoder
 * Method:    encode
 * Signature: ([S[SI[B)I
 */
JNIEXPORT void JNICALL Java_com_jiazhu_demo_encoder_Mp3EncoderTwo_encode
  (JNIEnv *, jobject);

/*
 * Class:     com_jiazhu_demo_Mp3Encoder
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jiazhu_demo_encoder_Mp3EncoderTwo_destroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
